### ISSUE TITLE
Example wanted, RGB/monochrome rendering

### ISSUE THREAD

**Issue by DavidBrainard** [DavidBrainard/RenderToolbox3#46]
The toolbox as we have demonstrated it is set up for spectral rendering. For some applications, features of the render toolbox may be highly useful, but spectral rendering will not be needed.  The use of spectral rendering then takes up time.

It would be nice to have examples that illustrate RGB or even monochromatic rendering, perhaps with the generically compiled versions of the renderers.

**Comment by gzmk** [comment]
Hi David, I am actually trying to do exactly this right now (monochromatic rendering) as I am fitting rendered images to some photos I took. This requires me to update the parameters of rendering at every step and re-render, which takes a very long time with spectral rendering. Is there a quick way of getting only monochromatic output that you might know of?
